### PR TITLE
Final_login_Register_page after cleaning

### PR DESCRIPTION
**Pull request by banumajan**
Hi, I have created a new branch(Banu_login_register ) using the master and made my final changes for login and registration pages. Please review and let me know if you find any issues.

### CODE REVIEW

**Review by kristina-sh — CHANGES_REQUESTED** [review]
The file footer.php was removed. I used this file in the menu.php. Can you, please, to add it again?

**Review by MelMethe — CHANGES_REQUESTED** [review]
As Kristina said, please add the footer back.

@kristina-sh do you also need the header? It is deleted here too.

**Comment by kristina-sh** [comment]
@MelMethe No, I don need the header, because mine is different as it contains a  "log-in" button.  I only need footer.

**Comment by banumajan** [comment]
I have added footer.php back  and pushed to my branch. Please let me know if you need the header as well.

**Review by MelMethe — APPROVED** [review]

**Review by kristina-sh — APPROVED** [review]

**Pull request merged**
